name: Python

on:
  schedule:
  - cron: "0 2 * * MON-FRI" # Runs at 02:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v3
        with:
          python-version: 3.11 # Install the python version needed

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute Python script # Run the python script to get the latest data
        run: python postprocess.py
